################################################################################
# Automatically-generated file. Do not edit!
################################################################################

SHELL = cmd.exe

# Each subdirectory must supply rules for building sources it contributes
lib_PRAC/uoc/circ_buffer.obj: C:/Users/jordi/Google\ Drive/beritheundeleted@gmail.com/03.\ UOC/workspaces/SE/2019-1-prac/lib_PRAC/uoc/circ_buffer.c $(GEN_OPTS) | $(GEN_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccs901/ccs/tools/compiler/ti-cgt-arm_18.12.3.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="C:/ti/ccs901/ccs/ccs_base/arm/include" --include_path="C:/Users/jordi/Google Drive/beritheundeleted@gmail.com/03. UOC/workspaces/SE/2019-1-prac/lib_PRAC/freertos/cortex-m4" --include_path="C:/Users/jordi/Google Drive/beritheundeleted@gmail.com/03. UOC/workspaces/SE/2019-1-prac/lib_PRAC/freertos/inc" --include_path="C:/Users/jordi/Google Drive/beritheundeleted@gmail.com/03. UOC/workspaces/SE/2019-1-prac/lib_PRAC/freertos/src" --include_path="C:/Users/jordi/Google Drive/beritheundeleted@gmail.com/03. UOC/workspaces/SE/2019-1-prac/lib_PRAC/inc" --include_path="C:/Users/jordi/Google Drive/beritheundeleted@gmail.com/03. UOC/workspaces/SE/2019-1-prac/lib_PRAC/msp432" --include_path="C:/Users/jordi/Google Drive/beritheundeleted@gmail.com/03. UOC/workspaces/SE/2019-1-prac/lib_PRAC/uoc" --include_path="C:/Users/jordi/Google Drive/beritheundeleted@gmail.com/03. UOC/workspaces/SE/2019-1-prac/lib_PRAC/screen" --include_path="C:/Users/jordi/Google Drive/beritheundeleted@gmail.com/03. UOC/workspaces/SE/2019-1-prac/lib_PRAC/graphics" --include_path="C:/ti/ccs901/ccs/ccs_base/arm/include/CMSIS" --include_path="C:/Users/jordi/Google Drive/beritheundeleted@gmail.com/03. UOC/workspaces/SE/2019-1-prac/PRAC-Projecte-2_FINAL" --include_path="C:/ti/ccs901/ccs/tools/compiler/ti-cgt-arm_18.12.3.LTS/include" --advice:power=all --define=__MSP432P401R__ --define=ccs -g --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="lib_PRAC/uoc/$(basename $(<F)).d_raw" --obj_directory="lib_PRAC/uoc" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

lib_PRAC/uoc/edu_boosterpack_accelerometer.obj: C:/Users/jordi/Google\ Drive/beritheundeleted@gmail.com/03.\ UOC/workspaces/SE/2019-1-prac/lib_PRAC/uoc/edu_boosterpack_accelerometer.c $(GEN_OPTS) | $(GEN_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccs901/ccs/tools/compiler/ti-cgt-arm_18.12.3.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="C:/ti/ccs901/ccs/ccs_base/arm/include" --include_path="C:/Users/jordi/Google Drive/beritheundeleted@gmail.com/03. UOC/workspaces/SE/2019-1-prac/lib_PRAC/freertos/cortex-m4" --include_path="C:/Users/jordi/Google Drive/beritheundeleted@gmail.com/03. UOC/workspaces/SE/2019-1-prac/lib_PRAC/freertos/inc" --include_path="C:/Users/jordi/Google Drive/beritheundeleted@gmail.com/03. UOC/workspaces/SE/2019-1-prac/lib_PRAC/freertos/src" --include_path="C:/Users/jordi/Google Drive/beritheundeleted@gmail.com/03. UOC/workspaces/SE/2019-1-prac/lib_PRAC/inc" --include_path="C:/Users/jordi/Google Drive/beritheundeleted@gmail.com/03. UOC/workspaces/SE/2019-1-prac/lib_PRAC/msp432" --include_path="C:/Users/jordi/Google Drive/beritheundeleted@gmail.com/03. UOC/workspaces/SE/2019-1-prac/lib_PRAC/uoc" --include_path="C:/Users/jordi/Google Drive/beritheundeleted@gmail.com/03. UOC/workspaces/SE/2019-1-prac/lib_PRAC/screen" --include_path="C:/Users/jordi/Google Drive/beritheundeleted@gmail.com/03. UOC/workspaces/SE/2019-1-prac/lib_PRAC/graphics" --include_path="C:/ti/ccs901/ccs/ccs_base/arm/include/CMSIS" --include_path="C:/Users/jordi/Google Drive/beritheundeleted@gmail.com/03. UOC/workspaces/SE/2019-1-prac/PRAC-Projecte-2_FINAL" --include_path="C:/ti/ccs901/ccs/tools/compiler/ti-cgt-arm_18.12.3.LTS/include" --advice:power=all --define=__MSP432P401R__ --define=ccs -g --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="lib_PRAC/uoc/$(basename $(<F)).d_raw" --obj_directory="lib_PRAC/uoc" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

lib_PRAC/uoc/edu_boosterpack_buttons.obj: C:/Users/jordi/Google\ Drive/beritheundeleted@gmail.com/03.\ UOC/workspaces/SE/2019-1-prac/lib_PRAC/uoc/edu_boosterpack_buttons.c $(GEN_OPTS) | $(GEN_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccs901/ccs/tools/compiler/ti-cgt-arm_18.12.3.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="C:/ti/ccs901/ccs/ccs_base/arm/include" --include_path="C:/Users/jordi/Google Drive/beritheundeleted@gmail.com/03. UOC/workspaces/SE/2019-1-prac/lib_PRAC/freertos/cortex-m4" --include_path="C:/Users/jordi/Google Drive/beritheundeleted@gmail.com/03. UOC/workspaces/SE/2019-1-prac/lib_PRAC/freertos/inc" --include_path="C:/Users/jordi/Google Drive/beritheundeleted@gmail.com/03. UOC/workspaces/SE/2019-1-prac/lib_PRAC/freertos/src" --include_path="C:/Users/jordi/Google Drive/beritheundeleted@gmail.com/03. UOC/workspaces/SE/2019-1-prac/lib_PRAC/inc" --include_path="C:/Users/jordi/Google Drive/beritheundeleted@gmail.com/03. UOC/workspaces/SE/2019-1-prac/lib_PRAC/msp432" --include_path="C:/Users/jordi/Google Drive/beritheundeleted@gmail.com/03. UOC/workspaces/SE/2019-1-prac/lib_PRAC/uoc" --include_path="C:/Users/jordi/Google Drive/beritheundeleted@gmail.com/03. UOC/workspaces/SE/2019-1-prac/lib_PRAC/screen" --include_path="C:/Users/jordi/Google Drive/beritheundeleted@gmail.com/03. UOC/workspaces/SE/2019-1-prac/lib_PRAC/graphics" --include_path="C:/ti/ccs901/ccs/ccs_base/arm/include/CMSIS" --include_path="C:/Users/jordi/Google Drive/beritheundeleted@gmail.com/03. UOC/workspaces/SE/2019-1-prac/PRAC-Projecte-2_FINAL" --include_path="C:/ti/ccs901/ccs/tools/compiler/ti-cgt-arm_18.12.3.LTS/include" --advice:power=all --define=__MSP432P401R__ --define=ccs -g --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="lib_PRAC/uoc/$(basename $(<F)).d_raw" --obj_directory="lib_PRAC/uoc" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

lib_PRAC/uoc/edu_boosterpack_rgb.obj: C:/Users/jordi/Google\ Drive/beritheundeleted@gmail.com/03.\ UOC/workspaces/SE/2019-1-prac/lib_PRAC/uoc/edu_boosterpack_rgb.c $(GEN_OPTS) | $(GEN_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccs901/ccs/tools/compiler/ti-cgt-arm_18.12.3.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="C:/ti/ccs901/ccs/ccs_base/arm/include" --include_path="C:/Users/jordi/Google Drive/beritheundeleted@gmail.com/03. UOC/workspaces/SE/2019-1-prac/lib_PRAC/freertos/cortex-m4" --include_path="C:/Users/jordi/Google Drive/beritheundeleted@gmail.com/03. UOC/workspaces/SE/2019-1-prac/lib_PRAC/freertos/inc" --include_path="C:/Users/jordi/Google Drive/beritheundeleted@gmail.com/03. UOC/workspaces/SE/2019-1-prac/lib_PRAC/freertos/src" --include_path="C:/Users/jordi/Google Drive/beritheundeleted@gmail.com/03. UOC/workspaces/SE/2019-1-prac/lib_PRAC/inc" --include_path="C:/Users/jordi/Google Drive/beritheundeleted@gmail.com/03. UOC/workspaces/SE/2019-1-prac/lib_PRAC/msp432" --include_path="C:/Users/jordi/Google Drive/beritheundeleted@gmail.com/03. UOC/workspaces/SE/2019-1-prac/lib_PRAC/uoc" --include_path="C:/Users/jordi/Google Drive/beritheundeleted@gmail.com/03. UOC/workspaces/SE/2019-1-prac/lib_PRAC/screen" --include_path="C:/Users/jordi/Google Drive/beritheundeleted@gmail.com/03. UOC/workspaces/SE/2019-1-prac/lib_PRAC/graphics" --include_path="C:/ti/ccs901/ccs/ccs_base/arm/include/CMSIS" --include_path="C:/Users/jordi/Google Drive/beritheundeleted@gmail.com/03. UOC/workspaces/SE/2019-1-prac/PRAC-Projecte-2_FINAL" --include_path="C:/ti/ccs901/ccs/tools/compiler/ti-cgt-arm_18.12.3.LTS/include" --advice:power=all --define=__MSP432P401R__ --define=ccs -g --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="lib_PRAC/uoc/$(basename $(<F)).d_raw" --obj_directory="lib_PRAC/uoc" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

lib_PRAC/uoc/helper.obj: C:/Users/jordi/Google\ Drive/beritheundeleted@gmail.com/03.\ UOC/workspaces/SE/2019-1-prac/lib_PRAC/uoc/helper.c $(GEN_OPTS) | $(GEN_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccs901/ccs/tools/compiler/ti-cgt-arm_18.12.3.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="C:/ti/ccs901/ccs/ccs_base/arm/include" --include_path="C:/Users/jordi/Google Drive/beritheundeleted@gmail.com/03. UOC/workspaces/SE/2019-1-prac/lib_PRAC/freertos/cortex-m4" --include_path="C:/Users/jordi/Google Drive/beritheundeleted@gmail.com/03. UOC/workspaces/SE/2019-1-prac/lib_PRAC/freertos/inc" --include_path="C:/Users/jordi/Google Drive/beritheundeleted@gmail.com/03. UOC/workspaces/SE/2019-1-prac/lib_PRAC/freertos/src" --include_path="C:/Users/jordi/Google Drive/beritheundeleted@gmail.com/03. UOC/workspaces/SE/2019-1-prac/lib_PRAC/inc" --include_path="C:/Users/jordi/Google Drive/beritheundeleted@gmail.com/03. UOC/workspaces/SE/2019-1-prac/lib_PRAC/msp432" --include_path="C:/Users/jordi/Google Drive/beritheundeleted@gmail.com/03. UOC/workspaces/SE/2019-1-prac/lib_PRAC/uoc" --include_path="C:/Users/jordi/Google Drive/beritheundeleted@gmail.com/03. UOC/workspaces/SE/2019-1-prac/lib_PRAC/screen" --include_path="C:/Users/jordi/Google Drive/beritheundeleted@gmail.com/03. UOC/workspaces/SE/2019-1-prac/lib_PRAC/graphics" --include_path="C:/ti/ccs901/ccs/ccs_base/arm/include/CMSIS" --include_path="C:/Users/jordi/Google Drive/beritheundeleted@gmail.com/03. UOC/workspaces/SE/2019-1-prac/PRAC-Projecte-2_FINAL" --include_path="C:/ti/ccs901/ccs/tools/compiler/ti-cgt-arm_18.12.3.LTS/include" --advice:power=all --define=__MSP432P401R__ --define=ccs -g --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="lib_PRAC/uoc/$(basename $(<F)).d_raw" --obj_directory="lib_PRAC/uoc" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

lib_PRAC/uoc/interrupts.obj: C:/Users/jordi/Google\ Drive/beritheundeleted@gmail.com/03.\ UOC/workspaces/SE/2019-1-prac/lib_PRAC/uoc/interrupts.c $(GEN_OPTS) | $(GEN_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccs901/ccs/tools/compiler/ti-cgt-arm_18.12.3.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="C:/ti/ccs901/ccs/ccs_base/arm/include" --include_path="C:/Users/jordi/Google Drive/beritheundeleted@gmail.com/03. UOC/workspaces/SE/2019-1-prac/lib_PRAC/freertos/cortex-m4" --include_path="C:/Users/jordi/Google Drive/beritheundeleted@gmail.com/03. UOC/workspaces/SE/2019-1-prac/lib_PRAC/freertos/inc" --include_path="C:/Users/jordi/Google Drive/beritheundeleted@gmail.com/03. UOC/workspaces/SE/2019-1-prac/lib_PRAC/freertos/src" --include_path="C:/Users/jordi/Google Drive/beritheundeleted@gmail.com/03. UOC/workspaces/SE/2019-1-prac/lib_PRAC/inc" --include_path="C:/Users/jordi/Google Drive/beritheundeleted@gmail.com/03. UOC/workspaces/SE/2019-1-prac/lib_PRAC/msp432" --include_path="C:/Users/jordi/Google Drive/beritheundeleted@gmail.com/03. UOC/workspaces/SE/2019-1-prac/lib_PRAC/uoc" --include_path="C:/Users/jordi/Google Drive/beritheundeleted@gmail.com/03. UOC/workspaces/SE/2019-1-prac/lib_PRAC/screen" --include_path="C:/Users/jordi/Google Drive/beritheundeleted@gmail.com/03. UOC/workspaces/SE/2019-1-prac/lib_PRAC/graphics" --include_path="C:/ti/ccs901/ccs/ccs_base/arm/include/CMSIS" --include_path="C:/Users/jordi/Google Drive/beritheundeleted@gmail.com/03. UOC/workspaces/SE/2019-1-prac/PRAC-Projecte-2_FINAL" --include_path="C:/ti/ccs901/ccs/tools/compiler/ti-cgt-arm_18.12.3.LTS/include" --advice:power=all --define=__MSP432P401R__ --define=ccs -g --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="lib_PRAC/uoc/$(basename $(<F)).d_raw" --obj_directory="lib_PRAC/uoc" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

lib_PRAC/uoc/msp432_launchpad_board.obj: C:/Users/jordi/Google\ Drive/beritheundeleted@gmail.com/03.\ UOC/workspaces/SE/2019-1-prac/lib_PRAC/uoc/msp432_launchpad_board.c $(GEN_OPTS) | $(GEN_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccs901/ccs/tools/compiler/ti-cgt-arm_18.12.3.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="C:/ti/ccs901/ccs/ccs_base/arm/include" --include_path="C:/Users/jordi/Google Drive/beritheundeleted@gmail.com/03. UOC/workspaces/SE/2019-1-prac/lib_PRAC/freertos/cortex-m4" --include_path="C:/Users/jordi/Google Drive/beritheundeleted@gmail.com/03. UOC/workspaces/SE/2019-1-prac/lib_PRAC/freertos/inc" --include_path="C:/Users/jordi/Google Drive/beritheundeleted@gmail.com/03. UOC/workspaces/SE/2019-1-prac/lib_PRAC/freertos/src" --include_path="C:/Users/jordi/Google Drive/beritheundeleted@gmail.com/03. UOC/workspaces/SE/2019-1-prac/lib_PRAC/inc" --include_path="C:/Users/jordi/Google Drive/beritheundeleted@gmail.com/03. UOC/workspaces/SE/2019-1-prac/lib_PRAC/msp432" --include_path="C:/Users/jordi/Google Drive/beritheundeleted@gmail.com/03. UOC/workspaces/SE/2019-1-prac/lib_PRAC/uoc" --include_path="C:/Users/jordi/Google Drive/beritheundeleted@gmail.com/03. UOC/workspaces/SE/2019-1-prac/lib_PRAC/screen" --include_path="C:/Users/jordi/Google Drive/beritheundeleted@gmail.com/03. UOC/workspaces/SE/2019-1-prac/lib_PRAC/graphics" --include_path="C:/ti/ccs901/ccs/ccs_base/arm/include/CMSIS" --include_path="C:/Users/jordi/Google Drive/beritheundeleted@gmail.com/03. UOC/workspaces/SE/2019-1-prac/PRAC-Projecte-2_FINAL" --include_path="C:/ti/ccs901/ccs/tools/compiler/ti-cgt-arm_18.12.3.LTS/include" --advice:power=all --define=__MSP432P401R__ --define=ccs -g --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="lib_PRAC/uoc/$(basename $(<F)).d_raw" --obj_directory="lib_PRAC/uoc" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

lib_PRAC/uoc/msp432_launchpad_temperature.obj: C:/Users/jordi/Google\ Drive/beritheundeleted@gmail.com/03.\ UOC/workspaces/SE/2019-1-prac/lib_PRAC/uoc/msp432_launchpad_temperature.c $(GEN_OPTS) | $(GEN_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccs901/ccs/tools/compiler/ti-cgt-arm_18.12.3.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="C:/ti/ccs901/ccs/ccs_base/arm/include" --include_path="C:/Users/jordi/Google Drive/beritheundeleted@gmail.com/03. UOC/workspaces/SE/2019-1-prac/lib_PRAC/freertos/cortex-m4" --include_path="C:/Users/jordi/Google Drive/beritheundeleted@gmail.com/03. UOC/workspaces/SE/2019-1-prac/lib_PRAC/freertos/inc" --include_path="C:/Users/jordi/Google Drive/beritheundeleted@gmail.com/03. UOC/workspaces/SE/2019-1-prac/lib_PRAC/freertos/src" --include_path="C:/Users/jordi/Google Drive/beritheundeleted@gmail.com/03. UOC/workspaces/SE/2019-1-prac/lib_PRAC/inc" --include_path="C:/Users/jordi/Google Drive/beritheundeleted@gmail.com/03. UOC/workspaces/SE/2019-1-prac/lib_PRAC/msp432" --include_path="C:/Users/jordi/Google Drive/beritheundeleted@gmail.com/03. UOC/workspaces/SE/2019-1-prac/lib_PRAC/uoc" --include_path="C:/Users/jordi/Google Drive/beritheundeleted@gmail.com/03. UOC/workspaces/SE/2019-1-prac/lib_PRAC/screen" --include_path="C:/Users/jordi/Google Drive/beritheundeleted@gmail.com/03. UOC/workspaces/SE/2019-1-prac/lib_PRAC/graphics" --include_path="C:/ti/ccs901/ccs/ccs_base/arm/include/CMSIS" --include_path="C:/Users/jordi/Google Drive/beritheundeleted@gmail.com/03. UOC/workspaces/SE/2019-1-prac/PRAC-Projecte-2_FINAL" --include_path="C:/ti/ccs901/ccs/tools/compiler/ti-cgt-arm_18.12.3.LTS/include" --advice:power=all --define=__MSP432P401R__ --define=ccs -g --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="lib_PRAC/uoc/$(basename $(<F)).d_raw" --obj_directory="lib_PRAC/uoc" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

lib_PRAC/uoc/timer_driver.obj: C:/Users/jordi/Google\ Drive/beritheundeleted@gmail.com/03.\ UOC/workspaces/SE/2019-1-prac/lib_PRAC/uoc/timer_driver.c $(GEN_OPTS) | $(GEN_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccs901/ccs/tools/compiler/ti-cgt-arm_18.12.3.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="C:/ti/ccs901/ccs/ccs_base/arm/include" --include_path="C:/Users/jordi/Google Drive/beritheundeleted@gmail.com/03. UOC/workspaces/SE/2019-1-prac/lib_PRAC/freertos/cortex-m4" --include_path="C:/Users/jordi/Google Drive/beritheundeleted@gmail.com/03. UOC/workspaces/SE/2019-1-prac/lib_PRAC/freertos/inc" --include_path="C:/Users/jordi/Google Drive/beritheundeleted@gmail.com/03. UOC/workspaces/SE/2019-1-prac/lib_PRAC/freertos/src" --include_path="C:/Users/jordi/Google Drive/beritheundeleted@gmail.com/03. UOC/workspaces/SE/2019-1-prac/lib_PRAC/inc" --include_path="C:/Users/jordi/Google Drive/beritheundeleted@gmail.com/03. UOC/workspaces/SE/2019-1-prac/lib_PRAC/msp432" --include_path="C:/Users/jordi/Google Drive/beritheundeleted@gmail.com/03. UOC/workspaces/SE/2019-1-prac/lib_PRAC/uoc" --include_path="C:/Users/jordi/Google Drive/beritheundeleted@gmail.com/03. UOC/workspaces/SE/2019-1-prac/lib_PRAC/screen" --include_path="C:/Users/jordi/Google Drive/beritheundeleted@gmail.com/03. UOC/workspaces/SE/2019-1-prac/lib_PRAC/graphics" --include_path="C:/ti/ccs901/ccs/ccs_base/arm/include/CMSIS" --include_path="C:/Users/jordi/Google Drive/beritheundeleted@gmail.com/03. UOC/workspaces/SE/2019-1-prac/PRAC-Projecte-2_FINAL" --include_path="C:/ti/ccs901/ccs/tools/compiler/ti-cgt-arm_18.12.3.LTS/include" --advice:power=all --define=__MSP432P401R__ --define=ccs -g --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="lib_PRAC/uoc/$(basename $(<F)).d_raw" --obj_directory="lib_PRAC/uoc" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

lib_PRAC/uoc/uart_driver.obj: C:/Users/jordi/Google\ Drive/beritheundeleted@gmail.com/03.\ UOC/workspaces/SE/2019-1-prac/lib_PRAC/uoc/uart_driver.c $(GEN_OPTS) | $(GEN_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccs901/ccs/tools/compiler/ti-cgt-arm_18.12.3.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="C:/ti/ccs901/ccs/ccs_base/arm/include" --include_path="C:/Users/jordi/Google Drive/beritheundeleted@gmail.com/03. UOC/workspaces/SE/2019-1-prac/lib_PRAC/freertos/cortex-m4" --include_path="C:/Users/jordi/Google Drive/beritheundeleted@gmail.com/03. UOC/workspaces/SE/2019-1-prac/lib_PRAC/freertos/inc" --include_path="C:/Users/jordi/Google Drive/beritheundeleted@gmail.com/03. UOC/workspaces/SE/2019-1-prac/lib_PRAC/freertos/src" --include_path="C:/Users/jordi/Google Drive/beritheundeleted@gmail.com/03. UOC/workspaces/SE/2019-1-prac/lib_PRAC/inc" --include_path="C:/Users/jordi/Google Drive/beritheundeleted@gmail.com/03. UOC/workspaces/SE/2019-1-prac/lib_PRAC/msp432" --include_path="C:/Users/jordi/Google Drive/beritheundeleted@gmail.com/03. UOC/workspaces/SE/2019-1-prac/lib_PRAC/uoc" --include_path="C:/Users/jordi/Google Drive/beritheundeleted@gmail.com/03. UOC/workspaces/SE/2019-1-prac/lib_PRAC/screen" --include_path="C:/Users/jordi/Google Drive/beritheundeleted@gmail.com/03. UOC/workspaces/SE/2019-1-prac/lib_PRAC/graphics" --include_path="C:/ti/ccs901/ccs/ccs_base/arm/include/CMSIS" --include_path="C:/Users/jordi/Google Drive/beritheundeleted@gmail.com/03. UOC/workspaces/SE/2019-1-prac/PRAC-Projecte-2_FINAL" --include_path="C:/ti/ccs901/ccs/tools/compiler/ti-cgt-arm_18.12.3.LTS/include" --advice:power=all --define=__MSP432P401R__ --define=ccs -g --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="lib_PRAC/uoc/$(basename $(<F)).d_raw" --obj_directory="lib_PRAC/uoc" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '


